config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations'}

  root 'items#index'

  scope '/admin' do
    resources :users, except: [:show], as: 'users'
    resources :items, except: [:index, :show], as: 'items'
  end

  resources :orders, only: [:index, :new, :create]

  get '/cart', to: 'orders#show_cart', as: 'cart'
  get '/cart/clear', to: 'orders#clear_cart', as: 'clear_cart'
  delete '/cart/:id', to: 'orders#remove_from_cart', as: 'remove_from_cart'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_descriptions, dependent: :destroy

  validates :name, presence: true
  validates :price, numericality: { greater_than: 0 }

  scope :search_by_name, -> (query) do
    where('lower(name) LIKE :query', query: "%#{query.downcase}%")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_descriptions, dependent: :destroy
end

app/models/order_description.rb
class OrderDescription < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders, dependent: :destroy
  has_many :order_descriptions, through: :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true

  enum role: { user: 'use', admin: 'admin'}

  scope :all_except, -> (user) do
    User.where.not(id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/admin_check.rb
module AdminCheck extend ActiveSupport::Concern
  def admin?
    redirect_to root_path, notice: 'Permission denied!' unless current_user.admin?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include AdminCheck

  before_action :authenticate_user!, except: [:index]
  before_action :admin?, except: [:index]

  def index
    unless params[:query].blank?
      @items = Item.search_by_name(params[:query])
      return
    end

    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)

    if @item.save
      redirect_to root_path, notice: 'Saved!'
    else
      render 'new'
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])

    if @item.update item_params
      redirect_to root_path, notice: 'Updated!'
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    flash[:notice] = @item.destroy ? 'Deleted!' : 'Failed to delete item!'

    redirect_to root_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = current_user.orders
  end

  def new
    save_order_to_session params[:item_id], params[:quantity].to_i

    appendix = params[:search_query].blank? ? '' : "?query=#{params[:search_query]}"
    flash[:notice] = 'Added to cart.'
    redirect_to root_path + appendix
  end

  def create
    order_to_save = init_order_to_save

    if order_to_save.save
      empty_session_cart
      redirect_to :root, notice: 'Purchased successfully!'
    else
      flash[:notice] = 'Failed to save order!'
      render 'show_cart'
    end
  end

  def show_cart
    map_orders_from_session
  end

  def clear_cart
    empty_session_cart

    redirect_to root_path, notice: 'Cart is clear'
  end

  def remove_from_cart
    session[:orders].delete_at params[:id].to_i
    map_orders_from_session
    redirect_to :cart
  end

  private

  def save_order_to_session(item_id, quantity)
    session[:orders] ||= []

    unless Item.find(item_id)
      flash[:notice] = 'Item no longer exists. Please reload the page.'
      return
    end

    if quantity > 0
      session[:orders] << { item_id: params[:item_id], quantity: params[:quantity] }
    else
      flash[:notice] = 'Enter positive quantity!'
    end
  end

  def map_orders_from_session
    return unless session[:orders].instance_of? Array

    @total_amount = 0

    @orders = session[:orders].each_with_index.map do |order, i|
      item = Item.find(order['item_id'])
      @total_amount += item.price * order['quantity'].to_i

      { index: i, item_id: item.id, name: item.name, price: item.price, quantity: order['quantity'] }
    end
  end

  def init_order_to_save
    order_to_save = current_user.orders.new
    amount = 0

    order_to_save.order_descriptions = session[:orders].map do |order|
      item = Item.find(order['item_id'])

      amount += item.price * order['quantity'].to_i
      OrderDescription.new(order: order_to_save, item: item, quantity: order['quantity'])
    end

    order_to_save.amount = amount
    order_to_save
  end

  def empty_session_cart
    session[:orders] = []
    @orders = []
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  protected

    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

    def configure_account_update_params
      devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include AdminCheck

  before_action :authenticate_user!
  before_action :admin?

  def index
    @users = User.all_except(current_user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)

    if @user.save
      redirect_to users_path, notice: 'User saved!'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to users_path, notice: 'User updated!'
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :role, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_with model: item do |form| %>
  <div class="my-2">
    <div><%= form.label :name, class: 'form-label' %></div>
    <div><%= form.text_field :name, autofocus: true, class: 'form-control' %></div>
    <div class="text-danger my-1">
      <% item.errors[:name]&.each do |message| %>
        <div>* <%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="my-2">
    <div><%= form.label :description, class: 'form-label' %></div>
    <div><%= form.text_area :description, class: 'form-control' %></div>
    <div class="text-danger my-1">
      <% item.errors[:description]&.each do |message| %>
        <div>* <%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="my-2">
    <div><%= form.label :price, class: 'form-label' %></div>
    <div><%= form.number_field :price, step: 0.01, min: 0.01, class: 'form-control' %></div>
    <div class="text-danger my-1">
      <% item.errors[:price]&.each do |message| %>
        <div>* <%= message %></div>
      <% end %>
    </div>
  </div>
  <div>
    <%= form.submit class: 'btn btn-primary my-3' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="devise-form m-auto">
  <h1>Edit <%= @item.name %></h1>

  <%= render 'form', item: @item %>
</div>

app/views/items/index.html.erb
<div class="d-flex flex-row mt-3 mx-1">
  <div class="me-auto">
    <% if current_user&.admin? %>
      <%= link_to '+ New', new_item_path, class: 'btn btn-sm btn-success' %>
    <% end %>
  </div>
  <%= form_with url: root_url, method: :get, class: 'row justify-content-end g-2' do |form| %>
    <div class="col-auto">
      <%= form.text_field :query, value: params[:query] || '', class: 'form-control form-control-sm' %>
    </div>
    <div class="col-auto">
      <%= form.submit 'Search', class: 'btn btn-outline-secondary btn-sm' %>
    </div>
  <% end %>
</div>
<% if @items.any? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.name %></td>
          <td><%= item.description %></td>
          <td><%= number_to_currency item.price %></td>
          <% if current_user %>
            <%= form_with url: new_order_url, method: :get do |form| %>
              <%= form.hidden_field :search_query, value: params[:query] || '' %>
              <%= form.hidden_field :item_id, value: item.id %>
              <td class="fit">
                <%= form.number_field :quantity, min: 1, value: 1, class: 'form-control form-control-sm quantity-input' %>
              </td>
              <td class="fit"><%= form.submit 'To cart', class: 'btn btn-sm btn-outline-success'%></td>
            <% end %>
            <% if current_user.admin? %>
              <td class="fit">
                <%= link_to 'Edit', edit_item_path(item), class: 'btn btn-sm btn-outline-primary' %>
              </td>
              <td class="fit">
                <%= link_to 'Delete', item_path(item), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' %>
              </td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3 class="text-center mt-3">No items found</h3>
<% end %>

app/views/items/new.html.erb
<div class="devise-form m-auto">
  <h1>New item</h1>

  <%= render 'form', item: @item %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="position-relative">
      <nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
        <div class="container-fluid">
          <%= link_to 'Rails store', root_path, class: 'navbar-brand', :'data-turbolinks' => false %>
          <button class="navbar-toggler me-auto" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <% if user_signed_in? %>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to 'Cart', cart_path, class: 'nav-link', :'data-turbolinks' => false %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Orders history', orders_path, class: 'nav-link' %>
                </li>
                <% if current_user.admin? %>
                  <li class="nav-item">
                    <%= link_to 'Users', users_path, class: 'nav-link' %>
                  </li>
                <% end %>
              </ul>
            </div>
            <div class="d-flex">
              <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link' %>
              <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger btn-sm mx-1 my-auto' %>
            </div>
          <% else %>
            <div class="d-flex navbar-nav">
              <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-outline-secondary btn-sm mx-1' %>
              <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-outline-success btn-sm mx-1' %>
            </div>
          <% end %>
        </div>
      </nav>
      <% unless notice.blank? %>
        <div class="alert alert-warning alert-dismissible fade show position-absolute top-100 w-100" role="alert">
          <%= notice %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    </div>
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/index.html.erb
<% if @orders.any? %>
  <h3 class="mb-3">Orders history</h3>
  <div class="accordion" id="accordionExample">
    <% @orders.each do |order| %>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#a<%= order.created_at.strftime('%s') %>" aria-expanded="false" aria-controls="collapseOne">
            <%= order.created_at.strftime('%H:%M %d.%m.%y') %> for <%= number_to_currency order.amount %>
          </button>
        </h2>
        <div id="a<%= order.created_at.strftime('%s') %>" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>Item</th>
                  <th>Price</th>
                  <th>Quantity</th>
                </tr>
              </thead>
              <tbody>
                <% order.order_descriptions.each do |desc| %>
                  <tr>
                    <td><%= desc.item.name %></td>
                    <td><%= number_to_currency desc.item.price %></td>
                    <td><%= desc.quantity %></td>
                  </tr>
                <% end %>
                <td class="table-dark" colspan="3">Total: <%= number_to_currency order.amount %></td>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <h3 class="text-center">No orders yet</h3>
<% end %>

app/views/orders/show_cart.html.erb
<% if @orders && @orders.length > 0 %>
  <div class="d-flex flex-row align-items-center">
    <div class="me-auto">
      <h3>Shopping cart</h3>
    </div>
    <div>
      <%= link_to 'Buy', orders_path, method: :post, class: 'btn btn-sm btn-success me-2' %>
    </div>
    <div>
      <%= link_to 'Empty cart', clear_cart_path, :'data-turbolinks' => false, class: 'btn btn-sm btn-danger' %>
    </div>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Quantity</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order|%>
        <tr>
          <td><%= order[:name] %></td>
          <td><%= number_to_currency order[:price] %></td>
          <td><%= order[:quantity] %></td>
          <td class="fit">
            <%= link_to 'remove', remove_from_cart_path(order[:index]), method: :delete, class: 'btn btn-sm btn-outline-danger' %>
          </td>
        </tr>
      <% end %>
      <tr>
        <td colspan="3" class="table-dark">
          Overall price: <%= number_to_currency @total_amount %>
        </td>
      </tr>
    </tbody>
  </table>
<% else %>
  <h3 class="text-center">Cart is empty</h3>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div class="my-2">
    <div><%= form.label :email, class: 'form-label' %></div>
    <div><%= form.text_field :email, autofocus: true, class: 'form-control' %></div>
    <div class="text-danger my-1">
      <% user.errors[:email]&.each do |message| %>
        <div>* <%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="my-2">
    <div><%= form.label :first_name, class: 'form-label'%></div>
    <div><%= form.text_field :first_name, class: 'form-control' %></div>
    <div class="text-danger my-1">
      <% user.errors[:first_name]&.each do |message| %>
        <div>* <%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="my-2">
    <div><%= form.label :last_name, class: 'form-label' %></div>
    <div><%= form.text_field :last_name, class: 'form-control' %></div>
    <div class="text-danger my-1">
      <% user.errors[:last_name]&.each do |message| %>
        <div>* <%= message %></div>
      <% end %>
    </div>
  </div>
  <div class="my-2">
    <div><%= form.label :role, class: 'form-label'%></div>
    <div><%= form.select :role, ['user', 'admin'], { selected: 'user' }, class: 'form-select' %></div>
    <div class="text-danger my-1">
      <% user.errors[:role]&.each do |message| %>
        <div>* <%= message %></div>
      <% end %>
    </div>
  </div>
  <% if new %>
    <div class="my-2">
      <div><%= form.label :password, class: 'form-label' %></div>
      <div><%= form.password_field :password, class: 'form-control' %></div>
      <div class="text-danger my-1">
        <% user.errors[:password]&.each do |message| %>
          <div>* <%= message %></div>
        <% end %>
      </div>
    </div>
  <% end %>
  <div>
    <%= form.submit class: 'btn btn-primary my-3' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="devise-form m-auto">
  <h1>Edit user</h1>

  <%= render 'form', user: @user, new: false %>
</div>

app/views/users/index.html.erb
<div class="d-flex flex-row align-items-center">
  <div class="me-auto">
    <h3>Users</h3>
  </div>
  <div>
    <%= link_to '+ New', new_user_path, class: 'btn btn-sm btn-success me-2' %>
  </div>
</div>

<% if @users.any? %>
  <table class="table">
    <thead>
      <tr>
        <th>E-mail</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Role</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.first_name %></td>
          <td><%= user.last_name %></td>
          <td><%= user.role %></td>
          <td class="fit"><%= link_to 'Edit', edit_user_path(user), class: 'btn btn-sm btn-outline-primary' %></td>
          <td class="fit"><%= link_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  No users
<% end %>

app/views/users/new.html.erb
<div class="devise-form m-auto">
  <h1>New user</h1>

  <%= render 'form', user: @user, new: true %>
</div>